name: ci

on: [push, pull_request]

jobs:
    ci:
        name: continous integration
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Clone repository
              uses: actions/checkout@v2

            - name: install Node
              uses: actions/setup-node@v2
              with:
                  node-version: "14"
                  cache: npm

            - name: install dependency
              run: npm i

            - name: typechecking
              run: npm run check

            - name: lint
              run: npm run lint
